

export const actionTypes = {
    LOADER: 'LOADER',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
    GET_WISHLISHT_PRODUCTS_SUCCESS: 'GET_WISHLISHT_PRODUCTS_SUCCESS',
    GET_WISHLISHT_PRODUCTS_FAIL: 'GET_WISHLISHT_PRODUCTS_FAIL',
    GET_CART_PRODUCTS_SUCCESS: 'GET_CART_PRODUCTS_SUCCESS',
    GET_CART_PRODUCTS_FAIL: 'GET_CART_PRODUCTS_FAIL',
    ADD_WISHLISHT_PRODUCTS_SUCCESS: 'ADD_WISHLISHT_PRODUCTS_SUCCESS',
    ADD_WISHLISHT_PRODUCTS_FAIL: 'ADD_WISHLISHT_PRODUCTS_FAIL',
    REMOVE_WISHLISHT_PRODUCTS_SUCCESS: 'REMOVE_WISHLISHT_PRODUCTS_SUCCESS',
    REMOVE_WISHLISHT_PRODUCTS_FAIL: 'REMOVE_WISHLISHT_PRODUCTS_FAIL',
    ADD_CART_PRODUCTS_SUCCESS: 'ADD_CART_PRODUCTS_SUCCESS',
    ADD_CART_PRODUCTS_FAIL: 'ADD_CART_PRODUCTS_FAIL',
    REMOVE_CART_PRODUCTS_SUCCESS: 'REMOVE_CART_PRODUCTS_SUCCESS',
    REMOVE_CART_PRODUCTS_FAIL: 'REMOVE_CART_PRODUCTS_FAIL'
}